### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by PeryMKamal** [PeryMKamal/T17-Sprint0C5#5]
We have to search for different types of merging conflicts to push and then pull by users

**Comment by OSobky** [comment]
I solved a merging conflict , it happened when i tried to pulled from the repository 
the conflict name :  refusing to merge unrelated histories
and i solved it by typing ( --allow-unrelated-histories ) flag 
for example : $ git pull origin master --allow-unrelated-histories

**Comment by Lozi97** [comment]
i already fix the conflicts and everything is fine 👍
